---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2023/12/18 15:10
---

local M = UnLua.Class()

function M:Initialize()
end

function M:ReceiveBeginPlay()
    self.Overridden.ReceiveBeginPlay(self)

    printf("ReceiveBeginPlay")

    self:LuaDoTest_MapTestEvent()
end

function M:LuaDoTest_MapTestEvent()
    GES.Register(CppEvents.MapTestEvent, {self, self.OnMapTestEvent})

    local MapValue = UE4.TMap(UE4.int32, UE4.FVector)
    MapValue:Add(520, UE4.FVector(1, 10, 100))
    MapValue:Add(521, UE4.FVector(5, 52, 520))

    GES.Dispatch(CppEvents.MapTestEvent, {GES.TMap, MapValue})
end

function M:OnMapTestEvent(EventData)
    printf("OnMapTestEvent Start")

    local MapValue = EventData:GetMap(UE4.int32, UE4.FVector, 0)
    dump_map(MapValue)

    printf("OnMapTestEvent End")
end

return M