---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2023/12/18 15:10
---

local M = UnLua.Class()

function M:Initialize()
end

function M:ReceiveBeginPlay()
    self.Overridden.ReceiveBeginPlay(self)

    printf("BP_GESTest:ReceiveBeginPlay")

    --GlobalEventSystem.On(Event.MyTestEvent, function(EventData)
    --    self:OnMyTestEvent(EventData)
    --end, true)

    GES.Register("MyTestEvent", { self, self.OnMyTestEvent})

    --GlobalEventSystem.Unregister("MyTestEvent", {self, self.OnMyTestEvent})

    local ArrayValue = UE4.TArray(UE4.int32)
    ArrayValue:Add(10)
    ArrayValue:Add(5)
    ArrayValue:Add(1)

    local EnumValue = UE4.EGESEventDataCppType.EDT_Integer

    local TestStruct = UE4.FGESTestStruct()
    TestStruct.IntValue = 120
    TestStruct.StrValue = "HelloLua"

    GES.Dispatch("MyTestEvent", { GES.TArray, ArrayValue}, { GES.Enum, EnumValue}, { GES.UStruct, TestStruct})
end

function M:OnMyTestEvent(EventData)
    printf("BP_GESTest:OnMyTestEvent Start")

    local ArrayValue = EventData:GetArray(UE4.int32, 0)
    for i=1, ArrayValue:Num() do
        printf("BP_GESTest:OnMyTestEvent ArrayValue[%d] = %d", i, ArrayValue:Get(i))
    end

    local EnumValue = EventData:GetEnum(1)
    printf("BP_GESTest:OnMyTestEvent Enum:%s IsEqualTo:[EDT_Integer, %s]", tostring(EnumValue), tostring(EnumValue == UE4.EGESEventDataCppType.EDT_Integer))

    local TestStruct = EventData:GetStruct(2)
    printf("BP_GESTest:OnMyTestEvent Struct:{%d, %s}", TestStruct.IntValue, TestStruct.StrValue)

    printf("BP_GESTest:OnMyTestEvent End")
end

return M