---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2023/12/18 15:10
---

--- Global event system for lua
local GlobalEventSystem = {
    --- GES Event Data Type
    Bool = "Bool",
    Integer = "Integer",
    Float = "Float",
    FString = "FString",
    FName = "FName",
    FText = "FText",
    Enum = "Enum",
    UStruct = "UStruct",
    UObject = "UObject",
    TArray = "TArray",
    TMap = "TMap",
    TSet = "TSet",
    --- GES Event Data Type
}
GES = GlobalEventSystem

--- Register global event for lua
--- @param string EventName ID Name, defined in blueprint
--- @param delegate Callback Lua Callback for this event, eg. {self, self.CallbackName}
function GlobalEventSystem.Register(EventName, Callback)
    UE4.UGESBPLibrary.RegisterEventLua(EventName, Callback)
end

--- Unregister global event for lua
--- @param string EventName Event ID Name, defined in blueprint
--- @param delegate Callback Lua Callback for this event, eg. {self, self.CallbackName}
function GlobalEventSystem.Unregister(EventName, Callback)
    UE4.UGESBPLibrary.UnregisterEventLua(EventName, Callback)
end

--- Dispatch global event from lua
--- @param string EventName Event ID Name, defined in blueprint
--- @param args ... Event params, eg. {ParamTypeName, Param}
function GlobalEventSystem.Dispatch(EventName, ...)
    local EventParams = {...}
    local EventData = UE4.FGESEventDataArray()
    EventData:SetEventID(EventName)

    for i,v in ipairs(EventParams) do
        local TypeName = v[1]
        local EventParam = v[2]
        if TypeName == GES.Bool then
            EventData:PushBool(EventParam)
        elseif TypeName == GES.Integer then
            EventData:PushInteger(EventParam)
        elseif TypeName == GES.Float then
            EventData:PushFloat(EventParam)
        elseif TypeName == GES.FString then
            EventData:PushString(EventParam)
        elseif TypeName == GES.FName then
            EventData:PushName(EventParam)
        elseif TypeName == GES.FText then
            EventData:PushText(EventParam)
        elseif TypeName == GES.Enum then
            EventData:PushEnum(EventParam)
        elseif TypeName == GES.UStruct then
            EventData:PushStruct(EventParam)
        elseif TypeName == GES.UObject then
            EventData:PushObject(EventParam)
        elseif TypeName == GES.TArray then
            EventData:PushArray(EventParam)
        elseif TypeName == GES.TMap then
            EventData:PushMap(EventParam)
        elseif TypeName == GES.TSet then
            EventData:PushSet(EventParam)
        end
        printf("GES.Dispatch[%d] %s %s", i, tostring(TypeName), tostring(EventParam))
    end

    UE4.UGESBPLibrary.DispatchEventLua(EventData)
end