---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2023/12/18 15:10
---

--- Global event system for lua
local GlobalEventSystem = {
    --- GES Event Data Type
    Bool    = "Bool",
    Integer = "Integer",
    Float   = "Float",
    String  = "FString",
    Name    = "FName",
    Text    = "FText",
    Enum    = "Enum",
    Struct  = "UStruct",
    Object  = "UObject",
    Array   = "TArray",
    Map     = "TMap",
    Set     = "TSet",
    --- GES Event Data Type
}
GES = GlobalEventSystem

--- Register global event for lua
--- @param table CppEvent Cpp event, defined in 'CppEvents.lua'
--- @param delegate Callback Lua Callback for this event, eg. {self, self.CallbackName}
function GlobalEventSystem.Register(CppEvent, Callback)
    UE4.UGESBPLibrary.RegisterEventLua(CppEvent.Name, Callback)
end

--- Unregister global event for lua
--- @param table CppEvent Cpp event, defined in 'CppEvents.lua'
--- @param delegate Callback Lua Callback for this event, eg. {self, self.CallbackName}
function GlobalEventSystem.Unregister(CppEvent, Callback)
    UE4.UGESBPLibrary.UnregisterEventLua(CppEvent.Name, Callback)
end

--- Dispatch global event from lua
--- @param table CppEvent Cpp event, defined in 'CppEvents.lua'
--- @param args ... Event params, eg. { ParamTypeName, Param }
function GlobalEventSystem.Dispatch(CppEvent, ...)
    local EventParams = {...}
    local EventData = UE4.FGESEventDataArray()
    EventData:SetEventID(CppEvent.Name)

    for i,v in ipairs(EventParams) do
        local TypeName = v[1]
        local EventParam = v[2]
        if TypeName == GES.Bool then
            EventData:PushBool(EventParam)
        elseif TypeName == GES.Integer then
            EventData:PushInteger(EventParam)
        elseif TypeName == GES.Float then
            EventData:PushFloat(EventParam)
        elseif TypeName == GES.String then
            EventData:PushString(EventParam)
        elseif TypeName == GES.Name then
            EventData:PushName(EventParam)
        elseif TypeName == GES.Text then
            EventData:PushText(EventParam)
        elseif TypeName == GES.Enum then
            EventData:PushEnum(EventParam)
        elseif TypeName == GES.Struct then
            EventData:PushStruct(EventParam)
        elseif TypeName == GES.Object then
            EventData:PushObject(EventParam)
        elseif TypeName == GES.Array then
            EventData:PushArray(EventParam)
        elseif TypeName == GES.Map then
            EventData:PushMap(EventParam)
        elseif TypeName == GES.Set then
            EventData:PushSet(EventParam)
        else
            printf_e("GES.Dispatch unsupported EventType:%s", tostring(TypeName))
        end
        --printf("GES.Dispatch EventName:%s DataType:%s Value:%s", tostring(CppEvent.Name), tostring(TypeName), tostring(EventParam))
    end

    UE4.UGESBPLibrary.DispatchEventLua(EventData)
end