---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2023/12/27 11:39
---

local PrintUEString = UE.UKismetSystemLibrary.PrintString

function printf(formatString, ...)
    print(string.format("[GES_Test]" .. formatString, ...))
end

function PrintScreen(text, color, duration)
    color = color or UE.FLinearColor(1, 1, 1, 1)
    duration = duration or 10
    PrintUEString(nil, text, true, false, color, duration)
end