---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixiaohua.
--- DateTime: 2023/12/18 17:24
---
local do_require = function()
    require "Common"
    require 'GlobalEventSystem.Enums'
    require 'GlobalEventSystem.GlobalEventSystem'

    print("Preload Lua OK!")
end

do_require()